// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface DeliverFunds$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "DeliverFunds";
  readonly sourceName: "contracts/DeliverFunds.sol";
  readonly abi: [{"inputs":[{"name":"target","type":"address"}],"payable":true,"stateMutability":"payable","type":"constructor"}];
  readonly bytecode: "0x6080604052604051604e380380604e83398181016040526020811015602357600080fd5b81019080805190602001909291905050508073ffffffffffffffffffffffffffffffffffffffff16fffe";
  readonly deployedBytecode: "0x6080604052600080fdfea265627a7a7230582093ffdc4d2adcc197782c845f006e7cc52d9025a498b6282c9a167ad6bd37be7564736f6c634300050a0032";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/DeliverFunds.sol";
  readonly buildInfoId: "solc-0_5_10-19f8968109a3c64db3a420b936261e87d1bc5a4e";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["DeliverFunds"]: DeliverFunds$Type;
    ["contracts/DeliverFunds.sol:DeliverFunds"]: DeliverFunds$Type;
  }
}